name: Sync Fork with Upstream

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: SOPT-all/35-APPJAM-WEB-CONFETI
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: main

      - name: Push changes to fork
        run: |
          git config user.name "daahyunk"
          git config user.email "ekgusdl0408@naver.com"
          git remote add upstream https://github.com/SOPT-all/35-APPJAM-WEB-CONFETI.git
          git fetch upstream
          git merge upstream/develop
          git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/daahyunk/35-APPJAM-WEB-CONFETI.git develop
